"use client";
import { useContext, useEffect } from "react";
import { AuthContext } from "@/context/AddContext";
import MobileHome from "@/components/mobile/homePage";

export default function HomePage() {
  const appContext = useContext(AuthContext);
  useEffect(() => {
    appContext.setNavbarState(2);
  }, []);

  interface IData {
    id: number;
    type: string;
    abbr: string;
    amount: number;
    price: number;
    delta: number;
    percent: number;
  }

  const data: IData[] = [
    {
      id: 1,
      type: "Bitcoin",
      abbr: "BTC",
      amount: 112.1,
      price: 6456.45,
      delta: 74.36,
      percent: 1.15,
    },
    {
      id: 2,
      type: "Ethereum",
      abbr: "ETH",
      amount: 20.9,
      price: 203.11,
      delta: -3.86,
      percent: -1.9,
    },
    {
      id: 3,
      type: "Ripple",
      abbr: "XRP",
      amount: 18.1,
      price: 8682.45,
      delta: 0.01,
      percent: 3.07,
    },
    {
      id: 4,
      type: "Bitcoin Cash",
      abbr: "BCH",
      amount: 7.6,
      price: 6456.45,
      delta: 74.36,
      percent: 1.15,
    },
    {
      id: 5,
      type: "Litecoin",
      abbr: "LTC",
      amount: 4.8,
      price: 788.54,
      delta: 0.07,
      percent: 1.28,
    },
    {
      id: 6,
      type: "Tron",
      abbr: "TRX",
      amount: 4.4,
      price: 8682.45,
      delta: -0.01,
      percent: -3.05,
    },
    {
      id: 7,
      type: "EOS",
      abbr: "EOS",
      amount: 3.1,
      price: 6456.45,
      delta: -0.67,
      percent: -1.28,
    },
    {
      id: 8,
      type: "Tether",
      abbr: "USDT",
      amount: 2.1,
      price: 0.983,
      delta: 0.01,
      percent: 1.04,
    },
    {
      id: 9,
      type: "Cardano",
      abbr: "ADA",
      amount: 3.1,
      price: 0.075,
      delta: -0.01,
      percent: -2.89,
    },
    {
      id: 1,
      type: "Bitcoin",
      abbr: "BTC",
      amount: 112.1,
      price: 6456.45,
      delta: 74.36,
      percent: 1.15,
    },
    {
      id: 2,
      type: "Ethereum",
      abbr: "ETH",
      amount: 20.9,
      price: 203.11,
      delta: -3.86,
      percent: -1.9,
    },
    {
      id: 3,
      type: "Ripple",
      abbr: "XRP",
      amount: 18.1,
      price: 8682.45,
      delta: 0.01,
      percent: 3.07,
    },
    {
      id: 4,
      type: "Bitcoin Cash",
      abbr: "BCH",
      amount: 7.6,
      price: 6456.45,
      delta: 74.36,
      percent: 1.15,
    },
    {
      id: 5,
      type: "Litecoin",
      abbr: "LTC",
      amount: 4.8,
      price: 788.54,
      delta: 0.07,
      percent: 1.28,
    },
    {
      id: 6,
      type: "Tron",
      abbr: "TRX",
      amount: 4.4,
      price: 8682.45,
      delta: -0.01,
      percent: -3.05,
    },
    {
      id: 7,
      type: "EOS",
      abbr: "EOS",
      amount: 3.1,
      price: 6456.45,
      delta: -0.67,
      percent: -1.28,
    },
    {
      id: 8,
      type: "Tether",
      abbr: "USDT",
      amount: 2.1,
      price: 0.983,
      delta: 0.01,
      percent: 1.04,
    },
    {
      id: 9,
      type: "Cardano",
      abbr: "ADA",
      amount: 3.1,
      price: 0.075,
      delta: -0.01,
      percent: -2.89,
    },
    {
      id: 1,
      type: "Bitcoin",
      abbr: "BTC",
      amount: 112.1,
      price: 6456.45,
      delta: 74.36,
      percent: 1.15,
    },
    {
      id: 2,
      type: "Ethereum",
      abbr: "ETH",
      amount: 20.9,
      price: 203.11,
      delta: -3.86,
      percent: -1.9,
    },
    {
      id: 3,
      type: "Ripple",
      abbr: "XRP",
      amount: 18.1,
      price: 8682.45,
      delta: 0.01,
      percent: 3.07,
    },
    {
      id: 4,
      type: "Bitcoin Cash",
      abbr: "BCH",
      amount: 7.6,
      price: 6456.45,
      delta: 74.36,
      percent: 1.15,
    },
    {
      id: 5,
      type: "Litecoin",
      abbr: "LTC",
      amount: 4.8,
      price: 788.54,
      delta: 0.07,
      percent: 1.28,
    },
    {
      id: 6,
      type: "Tron",
      abbr: "TRX",
      amount: 4.4,
      price: 8682.45,
      delta: -0.01,
      percent: -3.05,
    },
    {
      id: 7,
      type: "EOS",
      abbr: "EOS",
      amount: 3.1,
      price: 6456.45,
      delta: -0.67,
      percent: -1.28,
    },
    {
      id: 8,
      type: "Tether",
      abbr: "USDT",
      amount: 2.1,
      price: 0.983,
      delta: 0.01,
      percent: 1.04,
    },
    {
      id: 9,
      type: "Cardano",
      abbr: "ADA",
      amount: 3.1,
      price: 0.075,
      delta: -0.01,
      percent: -2.89,
    },
    {
      id: 1,
      type: "Bitcoin",
      abbr: "BTC",
      amount: 112.1,
      price: 6456.45,
      delta: 74.36,
      percent: 1.15,
    },
    {
      id: 2,
      type: "Ethereum",
      abbr: "ETH",
      amount: 20.9,
      price: 203.11,
      delta: -3.86,
      percent: -1.9,
    },
    {
      id: 3,
      type: "Ripple",
      abbr: "XRP",
      amount: 18.1,
      price: 8682.45,
      delta: 0.01,
      percent: 3.07,
    },
    {
      id: 4,
      type: "Bitcoin Cash",
      abbr: "BCH",
      amount: 7.6,
      price: 6456.45,
      delta: 74.36,
      percent: 1.15,
    },
    {
      id: 5,
      type: "Litecoin",
      abbr: "LTC",
      amount: 4.8,
      price: 788.54,
      delta: 0.07,
      percent: 1.28,
    },
    {
      id: 6,
      type: "Tron",
      abbr: "TRX",
      amount: 4.4,
      price: 8682.45,
      delta: -0.01,
      percent: -3.05,
    },
    {
      id: 7,
      type: "EOS",
      abbr: "EOS",
      amount: 3.1,
      price: 6456.45,
      delta: -0.67,
      percent: -1.28,
    },
    {
      id: 8,
      type: "Tether",
      abbr: "USDT",
      amount: 2.1,
      price: 0.983,
      delta: 0.01,
      percent: 1.04,
    },
    {
      id: 9,
      type: "Cardano",
      abbr: "ADA",
      amount: 3.1,
      price: 0.075,
      delta: -0.01,
      percent: -2.89,
    },
    {
      id: 1,
      type: "Bitcoin",
      abbr: "BTC",
      amount: 112.1,
      price: 6456.45,
      delta: 74.36,
      percent: 1.15,
    },
    {
      id: 2,
      type: "Ethereum",
      abbr: "ETH",
      amount: 20.9,
      price: 203.11,
      delta: -3.86,
      percent: -1.9,
    },
    {
      id: 3,
      type: "Ripple",
      abbr: "XRP",
      amount: 18.1,
      price: 8682.45,
      delta: 0.01,
      percent: 3.07,
    },
    {
      id: 4,
      type: "Bitcoin Cash",
      abbr: "BCH",
      amount: 7.6,
      price: 6456.45,
      delta: 74.36,
      percent: 1.15,
    },
    {
      id: 5,
      type: "Litecoin",
      abbr: "LTC",
      amount: 4.8,
      price: 788.54,
      delta: 0.07,
      percent: 1.28,
    },
    {
      id: 6,
      type: "Tron",
      abbr: "TRX",
      amount: 4.4,
      price: 8682.45,
      delta: -0.01,
      percent: -3.05,
    },
    {
      id: 7,
      type: "EOS",
      abbr: "EOS",
      amount: 3.1,
      price: 6456.45,
      delta: -0.67,
      percent: -1.28,
    },
    {
      id: 8,
      type: "Tether",
      abbr: "USDT",
      amount: 2.1,
      price: 0.983,
      delta: 0.01,
      percent: 1.04,
    },
    {
      id: 9,
      type: "Cardano",
      abbr: "ADA",
      amount: 3.1,
      price: 0.075,
      delta: -0.01,
      percent: -2.89,
    },
  ];

  return (
    <div className="flex justify-center items-center w-screen min-w-[400px] h-screen bg-[gray]">
      <MobileHome data={data} />
    </div>
  );
}
